/*
Ethan Downer 103619438

-- Create a new database called 'DatabaseName'
-- Connect to the 'master' database to run this snippet
USE master
GO
-- Create the new database if it does not exist already
IF NOT EXISTS (
    SELECT name
        FROM sys.databases
        WHERE name = N'S103619438'
)
CREATE DATABASE S103619438
GO
*/


/*
SUBJECT(SUBJCODE, DESCRIPTION)
PRIMARY KEY (SUBJCODE)

TEACHER(STAFFID, SURNAME, GIVENNAME)
PRIMARY KEY (STAFFID)

STUDENT(STUDENTID, SURNAME, GIVENNAME, GENDER)
PRIMARY KEY (STUDENTID)


SUBJECT OFFERING(SUBJCODE, YEAR, SEMESTER, FEE, STAFFID)
PRIMARY KEY(SUBJCODE, YEAR, SEMESTER)
FOREIGN KEY(SUBJCODE) REFERENCES SUBJECT
FOREIGN KEY(STAFFID) REFERENCES TEACHER


ENROLMENT(STUDENTID, SUBJCODE, YEAR, SEMESTER, DATEENROLLED, GRADE)
PRIMARY KEY(STUDENTID, SUBJCODE, YEAR, SEMESTER)
FOREIGN KEY(STUDENTID) REFERENCES STUDENT
FOREIGN KEY(SUBJCODE, YEAR, SEMESTER) REFERENCING SUBJECTOFFERING
*/



test